#!/bin/sh
# Smoke test that loads the real plugin entry files under standalone luau.
#
#   sh tests/smoke/run.sh                 load plugin/host.luau and
#                                         plugin/window.luau, then require the
#                                         manifest's lenses/blocks to match the
#                                         ones the host half defined
#   sh tests/smoke/run.sh MODULE...       additionally load each plugin module
#                                         (e.g. plugin/guard_host.luau) in the
#                                         half its name implies (*_window.luau:
#                                         window, else host) and call its
#                                         register() when it returns one
#
# Standalone luau cannot read files and gives required modules their own
# sandboxed globals, so every plugin/*.luau source is embedded into a
# generated bundle and executed with loadstring + setfenv against a strict
# stub `tern` (tests/smoke/stub.luau): an API the stub does not know, or one
# used in the wrong half, fails the run.
set -eu

cd "$(dirname "$0")/../.."
LUAU=${LUAU:-.tools/bin/luau}

gen=tests/smoke/.generated
mkdir -p "$gen"
out="$gen/bundle.luau"
tmp="$out.tmp.$$"
trap 'rm -f "$tmp"' EXIT INT TERM

# plugin.toml ids of [[lenses]] and [[blocks]] tables.
ids() { # $1 = table name
	awk -v want="[[$1]]" '
		/^\[\[/ { cur = $0; next }
		/^\[/ { cur = ""; next }
		cur == want && /^[ \t]*id[ \t]*=/ {
			v = $0; sub(/^[^=]*=[ \t]*"/, "", v); sub(/".*$/, "", v); print v
		}
	' plugin.toml
}

{
	printf -- '--!strict\n-- GENERATED by tests/smoke/run.sh; do not edit.\n'
	printf 'local sources: { [string]: string } = {\n'
	find plugin -type f -name '*.luau' | LC_ALL=C sort | while IFS= read -r f; do
		eq="="
		while grep -qF "]$eq" "$f"; do
			eq="$eq="
		done
		printf '\t["%s"] = [%s[\n' "$f" "$eq"
		cat "$f"
		printf ']%s],\n' "$eq"
	done
	printf '}\n'
	printf 'local lenses: { string } = {'
	ids lenses | while IFS= read -r id; do printf ' "%s",' "$id"; done
	printf ' }\n'
	printf 'local blocks: { string } = {'
	ids blocks | while IFS= read -r id; do printf ' "%s",' "$id"; done
	printf ' }\n'
	printf 'return { sources = sources, lenses = lenses, blocks = blocks }\n'
} >"$tmp"
mv "$tmp" "$out"
trap - EXIT INT TERM

exec "$LUAU" tests/smoke/load.luau -a "$@"
